// <auto-generated />
using AplikacijaGM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AplikacijaGM.Migrations
{
    [DbContext(typeof(ClientsContext))]
    [Migration("20190913113802_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AplikacijaGM.Models.Clients", b =>
                {
                    b.Property<int>("KlijentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("varchae=(50)");

                    b.Property<string>("Ljubimac")
                        .HasColumnType("varchae=(50)");

                    b.Property<string>("Vlasnik")
                        .IsRequired()
                        .HasColumnType("nvarchae=(250)");

                    b.Property<string>("Vrsta")
                        .HasColumnType("varchae=(50)");

                    b.HasKey("KlijentID");

                    b.ToTable("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
